import type { Metadata } from 'next';
import ToolLayout from '@/components/ToolLayout';
import ToolSidebar from '@/components/ToolSidebar';
import FaqSection from '@/components/FaqSection';
import IncorrectQuoteGeneratorDemo from './incorrect-quote-generator-demo';

export const metadata: Metadata = {
  title: 'Incorrect Quote Generator - Funny, Romantic & Angst',
  description:
    'Make your own incorrect quotes in seconds — add your characters’ names, pick funny, romantic, or angst, and get a fake conversation they never actually had. Free, no AI, runs in your browser.',
  alternates: {
    canonical: '/tools/incorrect-quote-generator',
  },
  openGraph: {
    title: 'Incorrect Quote Generator — Fake Conversations for Your Characters | TextFixHub',
    description:
      'Make your own incorrect quotes — add your characters’ names, pick funny, romantic, or angst, and get a fake conversation they never actually had. Free, no AI.',
    siteName: 'TextFixHub',
    type: 'website',
  },
  twitter: {
    card: 'summary',
    title: 'Incorrect Quote Generator — Fake Conversations for Your Characters | TextFixHub',
    description:
      'Make your own incorrect quotes — add your characters’ names, pick funny, romantic, or angst, and get a fake conversation they never actually had. Free, no AI.',
  },
};

const INCORRECT_QUOTE_FAQS = [
  {
    question: 'What is an incorrect quote generator?',
    answer:
      'An incorrect quote generator pairs a fictional dialogue template with your character names to create a fake conversation — something the characters would never actually say. It is a fandom staple for making funny, romantic, or angsty memes out of your favorite characters.',
  },
  {
    question: 'How does this incorrect quote generator work?',
    answer:
      'Type in your characters’ names (2 to 6), pick a mood — funny, romantic, or angst — and hit Generate. We pair a hand-written dialogue template with your names and output a ready-to-copy fake conversation. Everything runs locally in your browser.',
  },
  {
    question: 'Can I use my own character names?',
    answer:
      'Yes. That is the whole point. Add any names you like — original characters, your OTP, a whole cast — and the generator casts them into the dialogue. With up to 6 characters you can build multi-person fake conversations too.',
  },
  {
    question: 'Are these incorrect quotes made by AI?',
    answer:
      'No. Every template is hand-written by a human — there is no AI involved, no API call, and nothing sent to a server. If you specifically want a no-AI incorrect quote generator, this is it.',
  },
  {
    question: 'What moods are available?',
    answer:
      'Three: Funny (absurd, deadpan one-liners), Romantic (soft and earnest), and Angst (hurt and heartbreak). You can also leave it on Any to get a mix of all three.',
  },
  {
    question: 'How do I share an incorrect quote?',
    answer:
      'Click Copy Quote and paste it anywhere — Tumblr, AO3 author’s notes, Discord, or a caption. The copied format is “Character: line” per line, so it reads like a script excerpt.',
  },
];

export default function IncorrectQuoteGeneratorPage() {
  return (
    <ToolLayout pageName="Incorrect Quote Generator">
      <div className="mx-auto max-w-4xl px-4 py-8">
        <h1 className="text-3xl font-bold text-stone-900">
          Incorrect Quote Generator
        </h1>
        <p className="mt-2 text-lg text-stone-600">
          Generate a fake conversation your characters never had — funny,
          romantic, or angsty. Add your own names, no AI, free.
        </p>

        <section className="mt-8">
          <h2 className="text-xl font-semibold text-stone-800">
            Try It Out
          </h2>
          <div className="mt-4">
            <IncorrectQuoteGeneratorDemo />
          </div>
        </section>

        <section className="mt-10">
          <h2 className="text-xl font-semibold text-stone-800">
            How It Works
          </h2>
          <p className="mt-2 text-stone-600">
            Every incorrect quote starts as a hand-written dialogue template —
            a short scene with two or more speakers and a punchline. When you
            press Generate, the tool picks a template from the mood you chose
            and casts your character names into the speaker roles. The result
            is a fake conversation in their voice, ready to copy.
          </p>
          <p className="mt-3 text-stone-600">
            Because the templates are written by hand rather than generated by
            AI, the quotes keep the deadpan, meme-y tone that makes incorrect
            quotes fun — no robotic phrasing, no sign-ups, and nothing uploaded.
          </p>
        </section>

        <section className="mt-10">
          <h2 className="text-xl font-semibold text-stone-800">
            Moods &amp; Use Cases
          </h2>
          <ul className="mt-2 list-disc space-y-1 pl-6 text-stone-600">
            <li>
              <strong>Funny incorrect quotes</strong> — absurd plans, cursed
              objects, and “why are you like this” energy for comedy memes.
            </li>
            <li>
              <strong>Romantic incorrect quotes</strong> — soft confessions and
              “I would still choose you” lines for ship content.
            </li>
            <li>
              <strong>Angst incorrect quotes</strong> — “you lied to me” and
              “I waited for you” drama for hurt/comfort fics.
            </li>
            <li>
              <strong>Any</strong> — a mix across all three for surprise.
            </li>
          </ul>
        </section>

        <FaqSection faqs={INCORRECT_QUOTE_FAQS} />

        <ToolSidebar currentSlug="incorrect-quote-generator" />
      </div>
    </ToolLayout>
  );
}
