/** 150 common English nouns for the Random Sentence Generator */
export const NOUNS: string[] = [
  'airplane', 'apple', 'arm', 'army', 'baby', 'bag', 'ball', 'banana', 'band',
  'bank', 'basket', 'bath', 'bear', 'bed', 'bird', 'boat', 'book', 'bottle',
  'box', 'boy', 'brain', 'bread', 'bridge', 'brother', 'brush', 'building',
  'bush', 'butter', 'camera', 'captain', 'car', 'cat', 'chair', 'cheese',
  'child', 'church', 'city', 'clock', 'cloud', 'coast', 'coin', 'computer',
  'corner', 'cow', 'cup', 'daughter', 'day', 'desk', 'doctor', 'dog', 'door',
  'dream', 'dress', 'ear', 'earth', 'egg', 'engine', 'eye', 'face', 'family',
  'farm', 'father', 'field', 'finger', 'fire', 'fish', 'floor', 'flower',
  'foot', 'forest', 'friend', 'game', 'garden', 'gate', 'girl', 'glass',
  'goat', 'grass', 'gun', 'hair', 'hall', 'hand', 'hat', 'head', 'heart',
  'hill', 'home', 'horse', 'hospital', 'house', 'island', 'judge', 'key',
  'king', 'kitchen', 'knife', 'lady', 'lake', 'lamp', 'leg', 'letter',
  'library', 'lion', 'lip', 'machine', 'man', 'market', 'meal', 'meat',
  'milk', 'minute', 'money', 'monkey', 'moon', 'mother', 'mountain', 'mouse',
  'mouth', 'music', 'name', 'neck', 'night', 'nose', 'number', 'ocean',
  'office', 'painter', 'paper', 'park', 'party', 'path', 'pencil', 'phone',
  'picture', 'pig', 'plane', 'planet', 'plant', 'plate', 'pocket', 'police',
  'pool', 'queen', 'rabbit', 'rain', 'rice', 'ring', 'river', 'road', 'roof',
  'room', 'rose', 'school', 'sea', 'sheep', 'ship', 'shoe', 'sister', 'sky',
  'snake', 'snow', 'soldier', 'son', 'song', 'star', 'stick', 'stone',
  'store', 'storm', 'story', 'street', 'student', 'sun', 'table', 'teacher',
  'team', 'tiger', 'toe', 'tongue', 'tooth', 'town', 'train', 'tree',
  'truck', 'uncle', 'valley', 'village', 'voice', 'wall', 'war', 'water',
  'way', 'week', 'wife', 'window', 'winter', 'woman', 'wood', 'word', 'world',
  'yard', 'year',
];
