/** 1000+ common English nouns for the Random Noun Generator */
export const NOUN_LIST: string[] = [
  'ability', 'accident', 'account', 'action', 'activity', 'actor', 'addition',
  'address', 'advantage', 'advice', 'afternoon', 'age', 'agency', 'agreement',
  'air', 'airplane', 'airport', 'alarm', 'alcohol', 'ambition', 'amount',
  'analyst', 'anger', 'animal', 'answer', 'apartment', 'apple', 'application',
  'area', 'argument', 'arm', 'army', 'arrival', 'art', 'article', 'artist',
  'aspect', 'assignment', 'assistant', 'association', 'atmosphere', 'attack',
  'attention', 'attitude', 'audience', 'aunt', 'author', 'average', 'award',
  'baby', 'back', 'bag', 'balance', 'ball', 'banana', 'band', 'bank', 'bar',
  'baseball', 'basis', 'basket', 'bath', 'bathroom', 'battle', 'beach', 'bear',
  'beauty', 'bed', 'bedroom', 'beer', 'beginning', 'behavior', 'benefit', 'bike',
  'bill', 'bird', 'birthday', 'bit', 'blood', 'board', 'boat', 'body', 'bone',
  'book', 'border', 'boss', 'bottle', 'bottom', 'box', 'boy', 'boyfriend',
  'brain', 'branch', 'bread', 'breakfast', 'breath', 'bridge', 'brother',
  'budget', 'building', 'bus', 'business', 'butter', 'button', 'cabinet',
  'camera', 'campaign', 'candle', 'captain', 'car', 'card', 'career', 'carpet',
  'case', 'cash', 'cat', 'category', 'cause', 'celebration', 'cell', 'chair',
  'champion', 'chance', 'chapter', 'charity', 'cheese', 'chemistry', 'chest',
  'chicken', 'child', 'chocolate', 'choice', 'church', 'cigarette', 'city',
  'class', 'classroom', 'client', 'climate', 'clock', 'clothes', 'cloud', 'club',
  'coast', 'coffee', 'college', 'combination', 'committee', 'communication',
  'community', 'company', 'comparison', 'competition', 'complaint', 'computer',
  'concept', 'concern', 'conclusion', 'condition', 'confusion', 'connection',
  'consequence', 'context', 'contract', 'contribution', 'control',
  'conversation', 'cookie', 'copy', 'corner', 'cost', 'country', 'county',
  'courage', 'course', 'cousin', 'cow', 'cream', 'criticism', 'culture', 'cup',
  'currency', 'customer', 'dad', 'danger', 'data', 'database', 'daughter',
  'day', 'death', 'debate', 'debt', 'decision', 'definition', 'delivery',
  'demand', 'department', 'departure', 'description', 'design', 'desk', 'detail',
  'development', 'device', 'diamond', 'dinner', 'direction', 'director',
  'dirt', 'disaster', 'discipline', 'discussion', 'disease', 'disk', 'display',
  'distance', 'distribution', 'doctor', 'document', 'dog', 'door', 'drama',
  'drawer', 'drawing', 'dream', 'dress', 'drink', 'driver', 'ear', 'earth',
  'economics', 'economy', 'editor', 'education', 'effect', 'effort', 'egg',
  'election', 'elevator', 'emotion', 'employee', 'employer', 'end', 'energy',
  'engine', 'engineer', 'entertainment', 'enthusiasm', 'entry', 'environment',
  'error', 'estate', 'evening', 'event', 'exam', 'examination', 'example',
  'exchange', 'excitement', 'excuse', 'exercise', 'experience', 'expert',
  'explanation', 'expression', 'extension', 'eye', 'face', 'fact', 'failure',
  'family', 'farmer', 'father', 'feature', 'feedback', 'field', 'figure',
  'film', 'finger', 'fire', 'fish', 'flight', 'flower', 'food', 'foot',
  'football', 'force', 'forest', 'form', 'fortune', 'foundation', 'friend',
  'fruit', 'funeral', 'future', 'game', 'garden', 'gate', 'gene', 'girl',
  'girlfriend', 'glass', 'goal', 'god', 'gold', 'golf', 'government',
  'grandmother', 'grass', 'grocery', 'group', 'growth', 'guest', 'guidance',
  'guitar', 'gun', 'hair', 'hall', 'hand', 'hat', 'head', 'health', 'heart',
  'height', 'highway', 'hill', 'history', 'home', 'homework', 'honey', 'hope',
  'horse', 'hospital', 'hotel', 'house', 'housing', 'idea', 'image',
  'imagination', 'impact', 'importance', 'impression', 'improvement', 'income',
  'independence', 'indication', 'industry', 'information', 'insect', 'insight',
  'inspector', 'instruction', 'insurance', 'intention', 'interaction',
  'interest', 'internet', 'introduction', 'investment', 'island', 'issue',
  'item', 'jacket', 'job', 'judge', 'judgment', 'juice', 'key', 'king',
  'kitchen', 'knowledge', 'lab', 'ladder', 'lady', 'lake', 'language', 'law',
  'leader', 'league', 'leather', 'letter', 'library', 'life', 'light',
  'lip', 'list', 'literature', 'location', 'loss', 'love', 'luck', 'lunch',
  'machine', 'magazine', 'mail', 'mall', 'man', 'management', 'manager', 'map',
  'market', 'marriage', 'math', 'meal', 'meaning', 'measurement', 'meat',
  'media', 'medicine', 'medium', 'member', 'memory', 'menu', 'message', 'metal',
  'method', 'midnight', 'milk', 'mind', 'mixture', 'mode', 'mom', 'moment',
  'money', 'monitor', 'month', 'mood', 'morning', 'mother', 'mountain', 'mouse',
  'mouth', 'movie', 'mud', 'muscle', 'museum', 'music', 'name', 'nation',
  'nature', 'neck', 'negotiation', 'network', 'news', 'newspaper', 'night',
  'noise', 'nose', 'note', 'number', 'nurse', 'object', 'obligation', 'office',
  'oil', 'operation', 'opinion', 'opportunity', 'orange', 'order',
  'organization', 'outcome', 'oven', 'owner', 'pain', 'painting', 'paper',
  'parent', 'park', 'parking', 'part', 'party', 'passenger', 'passion',
  'patience', 'pattern', 'payment', 'penalty', 'pencil', 'people', 'percentage',
  'performance', 'period', 'permission', 'person', 'personality', 'perspective',
  'philosophy', 'phone', 'photo', 'physics', 'piano', 'picture', 'pie', 'place',
  'plan', 'plane', 'planet', 'plant', 'plastic', 'platform', 'player', 'poem',
  'poet', 'police', 'policy', 'politics', 'pollution', 'population', 'position',
  'possession', 'possibility', 'potato', 'power', 'practice', 'preference',
  'preparation', 'president', 'pressure', 'price', 'priority', 'problem',
  'procedure', 'process', 'product', 'profession', 'professor', 'profit',
  'program', 'promotion', 'property', 'proposal', 'protection', 'psychology',
  'purpose', 'quality', 'quantity', 'queen', 'question', 'radio', 'rain',
  'ratio', 'reaction', 'reality', 'reason', 'reception', 'recipe', 'recognition',
  'recommendation', 'record', 'reflection', 'region', 'relation', 'relationship',
  'religion', 'replacement', 'report', 'republic', 'reputation', 'request',
  'research', 'resolution', 'resource', 'response', 'responsibility', 'restaurant',
  'result', 'revenue', 'revolution', 'rice', 'river', 'road', 'rock', 'role',
  'room', 'rule', 'safety', 'salad', 'salt', 'sample', 'sandwich', 'scene',
  'schedule', 'school', 'science', 'screen', 'sea', 'season', 'secretary',
  'section', 'security', 'selection', 'sense', 'series', 'service', 'session',
  'shape', 'shirt', 'shoe', 'shop', 'side', 'sign', 'signature', 'silver',
  'singer', 'sir', 'sister', 'site', 'situation', 'skill', 'skin', 'sky',
  'snow', 'society', 'software', 'soil', 'son', 'song', 'sort', 'soup',
  'source', 'space', 'speech', 'spirit', 'sport', 'spring', 'star', 'state',
  'statement', 'steak', 'step', 'stock', 'stomach', 'store', 'storm', 'story',
  'stranger', 'strategy', 'street', 'stress', 'structure', 'student', 'studio',
  'style', 'subject', 'success', 'suggestion', 'summer', 'sun', 'supermarket',
  'surgery', 'surprise', 'sweetheart', 'swimming', 'sympathy', 'system',
  'table', 'tale', 'task', 'tax', 'tea', 'teacher', 'team', 'tear',
  'technology', 'television', 'temperature', 'tennis', 'tension', 'term',
  'test', 'thanks', 'theory', 'thing', 'thought', 'throat', 'ticket', 'time',
  'tongue', 'tool', 'tooth', 'topic', 'tour', 'town', 'tradition', 'trainer',
  'transportation', 'tree', 'trip', 'trouble', 'truck', 'trust', 'truth', 'tune',
  'uncle', 'understanding', 'union', 'unit', 'university', 'user', 'valley',
  'value', 'variation', 'vehicle', 'version', 'video', 'view', 'village',
  'virus', 'voice', 'volume', 'wall', 'war', 'warning', 'water', 'wave', 'way',
  'weakness', 'wealth', 'weather', 'web', 'wedding', 'week', 'weight', 'wife',
  'wind', 'window', 'wine', 'winter', 'wish', 'woman', 'wood', 'word', 'work',
  'worker', 'world', 'writer', 'yard', 'year', 'youth',
  // ===== Additional 600+ nouns (1000+ total) =====
  'absence', 'abuse', 'accent', 'access', 'accommodation', 'achievement',
  'acid', 'acquaintance', 'acquisition', 'acre', 'adaptation', 'adjustment',
  'administration', 'admiration', 'admission', 'adoption', 'adventure',
  'advertisement', 'affair', 'affection', 'aftermath', 'agenda', 'agriculture',
  'aid', 'aim', 'aisle', 'album', 'alliance', 'allowance', 'ally', 'altar',
  'alteration', 'altitude', 'aluminum', 'amateur', 'amazement', 'ambassador',
  'ambulance', 'amendment', 'ammunition', 'ancestor', 'anchor', 'angel',
  'angle', 'ankle', 'anniversary', 'announcement', 'ant', 'anticipation',
  'anxiety', 'apology', 'apparatus', 'appeal', 'appearance', 'appetite',
  'appliance', 'appointment', 'appreciation', 'approval', 'architect',
  'architecture', 'archive', 'arena', 'arithmetic', 'armor', 'arrangement',
  'arrow', 'ash', 'assault', 'assembly', 'assessment', 'asset', 'assumption',
  'astronomer', 'athlete', 'atom', 'attachment', 'attempt', 'attendance',
  'attic', 'attraction', 'auction', 'authority', 'autumn', 'avenue', 'aviation',
  'bacteria', 'badge', 'baker', 'balcony', 'ballet', 'balloon', 'ballot',
  'banner', 'bargain', 'barn', 'barrel', 'barrier', 'basement', 'basin',
  'battery', 'bay', 'beam', 'bean', 'beard', 'beast', 'bee', 'beetle',
  'bell', 'belt', 'bench', 'betrayal', 'billion', 'biology', 'biscuit',
  'bishop', 'blanket', 'blast', 'blessing', 'block', 'blossom', 'blueprint',
  'boiler', 'bolt', 'bomb', 'bond', 'bonus', 'bookstore', 'booth', 'border',
  'bow', 'bowl', 'bracelet', 'brake', 'brand', 'brass', 'breeze', 'brick',
  'bride', 'broadcast', 'broom', 'brush', 'bubble', 'bucket', 'bullet', 'bull',
  'bulletin', 'bunch', 'burden', 'bureau', 'burst', 'bush', 'butterfly',
  'cabin', 'cable', 'cage', 'calculator', 'calendar', 'camel', 'canal',
  'cancer', 'candidate', 'canvas', 'capability', 'capacity', 'capital',
  'caravan', 'carbon', 'cargo', 'carpenter', 'carriage', 'carrot', 'cart',
  'castle', 'casualty', 'catalog', 'cathedral', 'cattle', 'caution', 'cave',
  'cavity', 'ceiling', 'cellar', 'cement', 'cemetery', 'ceremony', 'certificate',
  'chain', 'challenge', 'chamber', 'champagne', 'channel', 'chaos', 'chapel',
  'character', 'charge', 'charm', 'chart', 'chassis', 'cheek', 'cherry',
  'chess', 'chief', 'chimney', 'chip', 'choir', 'chunk', 'circuit', 'circular',
  'circumstance', 'citizen', 'civilization', 'claim', 'clan', 'clarification',
  'clarity', 'clash', 'clay', 'clergy', 'clerk', 'click', 'cliff', 'clinic',
  'clip', 'closet', 'closure', 'cloth', 'clue', 'cluster', 'coach', 'coal',
  'coalition', 'coastline', 'code', 'coffin', 'coincidence', 'collapse', 'collar',
  'colleague', 'collection', 'colonel', 'colony', 'column', 'combat', 'comedy',
  'comfort', 'command', 'commander', 'comment', 'commerce', 'commission',
  'commitment', 'commodity', 'companion', 'compartment', 'compass', 'compensation',
  'compliment', 'component', 'composer', 'composition', 'compound', 'compromise',
  'concentration', 'conception', 'concert', 'concession', 'concrete', 'conductor',
  'conference', 'confession', 'confidence', 'configuration', 'conflict',
  'confrontation', 'congregation', 'congress', 'conquest', 'conscience',
  'consciousness', 'consensus', 'consent', 'conservation', 'consideration',
  'consistency', 'conspiracy', 'constitution', 'constraint', 'construction',
  'consultation', 'consumer', 'consumption', 'contact', 'contemplation',
  'contempt', 'continent', 'contingent', 'contradiction', 'convenience',
  'convention', 'conviction', 'cooperation', 'copper', 'coral', 'cord',
  'core', 'corporation', 'correction', 'correlation', 'correspondence',
  'corridor', 'corruption', 'cottage', 'cotton', 'council', 'counsel',
  'counterpart', 'countess', 'couple', 'courtyard', 'coverage', 'craft',
  'crash', 'crawl', 'creature', 'credit', 'crew', 'cricket', 'crime',
  'crisis', 'criterion', 'crop', 'crossroad', 'crowd', 'crown', 'cruelty',
  'crystal', 'cure', 'curiosity', 'curtain', 'curve', 'cushion', 'custody',
  'custom', 'cycle', 'cylinder', 'damage', 'damp', 'dawn', 'deadline', 'deal',
  'dealer', 'decay', 'deception', 'declaration', 'decline', 'decoration',
  'decrease', 'deed', 'defeat', 'defect', 'defense', 'deficit', 'delegation',
  'delight', 'democracy', 'demonstration', 'denial', 'density', 'dentist',
  'departure', 'dependence', 'deposit', 'depression', 'deputy', 'descent',
  'desert', 'desire', 'desk', 'despair', 'destination', 'destiny', 'destruction',
  'detective', 'determination', 'diagram', 'dialogue', 'diary', 'dictator',
  'dictionary', 'diet', 'digestion', 'dignity', 'dilemma', 'dimension',
  'diplomat', 'disability', 'disappointment', 'discharge', 'discount',
  'discovery', 'discretion', 'disorder', 'disposal', 'dispute', 'dissent',
  'dissertation', 'distinction', 'distress', 'district', 'dive', 'diversity',
  'division', 'divorce', 'dock', 'doctrine', 'doll', 'domain', 'dominance',
  'donation', 'donor', 'dose', 'doubt', 'downtown', 'draft', 'dragon',
  'drain', 'drift', 'drought', 'drum', 'duchess', 'duke', 'duration', 'dust',
  'dynasty', 'eagle', 'earthquake', 'echo', 'ecology', 'edge', 'edition',
  'efficiency', 'elbow', 'element', 'elephant', 'elite', 'embassy', 'embrace',
  'emergence', 'emergency', 'emission', 'emperor', 'empire', 'enclosure',
  'encounter', 'encouragement', 'enemy', 'enforcement', 'engagement', 'enjoyment',
  'enquiry', 'enterprise', 'enthusiasm', 'entrance', 'envelope', 'epidemic',
  'episode', 'equality', 'equation', 'equipment', 'era', 'escape', 'essay',
  'essence', 'establishment', 'ethics', 'evaluation', 'evolution', 'exaggeration',
  'exception', 'excess', 'exclusion', 'excursion', 'execution', 'exhibition',
  'exile', 'existence', 'expansion', 'expectation', 'expedition', 'expenditure',
  'expense', 'experiment', 'expertise', 'exploration', 'explosion', 'export',
  'exposure', 'extinction', 'extract', 'fabric', 'facility', 'factory', 'faculty',
  'faith', 'fame', 'fantasy', 'fare', 'farewell', 'fashion', 'fault', 'favor',
  'feast', 'feather', 'federation', 'ferry', 'festival', 'fever', 'fiber',
  'fiction', 'finding', 'fireplace', 'firm', 'fixture', 'flame', 'fleet',
  'flesh', 'flock', 'flood', 'floor', 'flour', 'fluid', 'focus', 'fog',
  'fold', 'folk', 'follower', 'footstep', 'forecast', 'foreigner', 'format',
  'formation', 'formula', 'fortress', 'forum', 'fossil', 'fountain', 'fraction',
  'fracture', 'fragment', 'framework', 'franchise', 'fraud', 'freedom',
  'frequency', 'friction', 'frontier', 'frost', 'fuel', 'fulfillment',
  'function', 'fund', 'fur', 'furnace', 'fury', 'fusion', 'galaxy', 'gallery',
  'gallon', 'gang', 'garage', 'garbage', 'garlic', 'garment', 'gasoline',
  'gathering', 'gaze', 'gear', 'gender', 'generosity', 'genius', 'genre',
  'gentleman', 'geography', 'gesture', 'ghost', 'giant', 'gland', 'glare',
  'globe', 'glimpse', 'glory', 'goddess', 'goodbye', 'goodness', 'gorge',
  'governor', 'grace', 'grade', 'grain', 'grammar', 'grandchild', 'grandfather',
  'graph', 'grave', 'gravity', 'greenhouse', 'grief', 'grin', 'grudge',
  'guarantee', 'guardian', 'guerrilla', 'guilt', 'gym', 'habitat', 'harbor',
  'hardware', 'harm', 'harmony', 'harvest', 'hatred', 'hazard', 'heading',
  'headquarters', 'heal', 'heap', 'heating', 'heaven', 'hedge', 'heel',
  'helicopter', 'helmet', 'herb', 'herd', 'heritage', 'hero', 'highlight',
  'hip', 'hire', 'historian', 'hobby', 'holder', 'hollow', 'honor', 'hook',
  'horizon', 'horror', 'host', 'hostility', 'household', 'humanity', 'humor',
  'hunger', 'hunt', 'hurricane', 'hut', 'hydrogen', 'hypothesis', 'icon',
  'ideal', 'identification', 'identity', 'ideology', 'ignorance', 'illusion',
  'illustration', 'immigrant', 'immigration', 'implement', 'implication',
  'import', 'imposition', 'impulse', 'inability', 'incidence', 'incident',
  'incline', 'inclusion', 'indicator', 'individual', 'indulgence', 'inequality',
  'infant', 'infection', 'inflation', 'ingredient', 'inhabitant', 'inheritance',
  'initiative', 'injection', 'injury', 'injustice', 'ink', 'innocence',
  'innovation', 'input', 'inquiry', 'insertion', 'inspection', 'inspiration',
  'installation', 'instinct', 'institute', 'institution', 'instrument',
  'insult', 'integral', 'integrity', 'intellectual', 'intelligence', 'intensity',
  'interference', 'interior', 'interpretation', 'interval', 'intervention',
  'invasion', 'invention', 'investigator', 'invitation', 'involvement', 'irony',
  'isolation', 'jail', 'jaw', 'jazz', 'jealousy', 'jewelry', 'joint',
  'journal', 'journalist', 'journey', 'joy', 'jungle', 'jurisdiction', 'jury',
  'justice', 'justification', 'keeper', 'kernel', 'keyboard', 'kidney', 'kind',
  'kingdom', 'kiss', 'knight', 'knot', 'label', 'laboratory', 'labor', 'lack',
  'landing', 'landlord', 'landmark', 'landscape', 'lane', 'lap', 'laser',
  'latitude', 'latter', 'laughter', 'launch', 'laundry', 'lawsuit', 'layer',
  'layout', 'leaf', 'leak', 'leap', 'lease', 'lecture', 'legacy', 'legend',
  'legislature', 'legitimacy', 'leisure', 'lemon', 'length', 'lens', 'lesson',
  'liability', 'liberty', 'license', 'lid', 'lifetime', 'likelihood', 'limb',
  'limitation', 'linen', 'liver', 'living', 'lobby', 'locomotive', 'logic',
  'loyalty', 'luggage', 'lumber', 'luxury', 'magic', 'magistrate', 'magnet',
  'magnitude', 'mainland', 'maintenance', 'majesty', 'majority', 'maker',
  'makeup', 'manner', 'manufacturer', 'manuscript', 'marathon', 'margin',
  'marker', 'marsh', 'mask', 'mass', 'masterpiece', 'mate', 'material',
  'matter', 'maximum', 'maze', 'mechanic', 'mechanism', 'medal', 'melody',
  'membership', 'memorial', 'mentality', 'merchant', 'mercy', 'merger',
  'merit', 'mess', 'metaphor', 'mileage', 'mineral', 'miniature', 'minimum',
  'minister', 'ministry', 'minority', 'miracle', 'misery', 'missile', 'mission',
  'mistake', 'mobility', 'modification', 'molecule', 'monastery', 'monk',
  'monopoly', 'monster', 'monument', 'morality', 'mortality', 'mortgage',
  'mosaic', 'motion', 'motivation', 'motor', 'murmur', 'mystery', 'myth',
  'narrative', 'navigator', 'necessity', 'needle', 'neglect', 'neighbor',
  'neighborhood', 'nerve', 'nest', 'net', 'neutrality', 'niche', 'nobility',
  'nonsense', 'notebook', 'notion', 'novel', 'nucleus', 'nursery', 'nutrient',
  'oath', 'obedience', 'obsession', 'obstacle', 'occasion', 'occupation',
  'offense', 'offering', 'officer', 'opera', 'operator', 'opponent', 'opposition',
  'optimism', 'option', 'orchestra', 'organ', 'organism', 'orientation',
  'origin', 'original', 'ornament', 'outfit', 'outline', 'output', 'outrage',
  'outsider', 'oval', 'overcoat', 'overload', 'overtime', 'oxygen', 'oyster',
  'pace', 'pack', 'package', 'pad', 'page', 'palace', 'palm', 'panic',
  'paradox', 'paragraph', 'parameter', 'parcel', 'parish', 'parliament',
  'participant', 'particle', 'partnership', 'passage', 'passport', 'password',
  'pastor', 'pasture', 'patch', 'patent', 'path', 'patriot', 'patrol',
  'patron', 'pause', 'peak', 'peasant', 'peer', 'penalty', 'peninsula',
  'pension', 'pepper', 'perception', 'perfection', 'peril', 'permit',
  'petition', 'petrol', 'phase', 'phenomenon', 'photographer', 'phrase',
  'physician', 'physicist', 'pill', 'pillar', 'pillow', 'pin', 'pine',
  'pioneer', 'pit', 'pitch', 'plague', 'plain', 'plaster', 'plate', 'plea',
  'pleasure', 'pledge', 'plot', 'plunge', 'pocket', 'poison', 'pole',
  'polish', 'politician', 'pond', 'pool', 'pop', 'porch', 'port', 'porter',
  'portion', 'portrait', 'post', 'poster', 'pot', 'potential', 'pottery',
  'poverty', 'powder', 'precedent', 'precision', 'predator', 'prediction',
  'prejudice', 'premise', 'premium', 'prescription', 'presence', 'preservation',
  'presidency', 'prey', 'pride', 'priest', 'prince', 'princess', 'principal',
  'principle', 'printer', 'privacy', 'privilege', 'probability', 'probe',
  'proceeding', 'proceeds', 'proclamation', 'producer', 'profile', 'projection',
  'promise', 'proof', 'propaganda', 'prophet', 'proportion', 'prosecution',
  'prospect', 'prosperity', 'protein', 'protest', 'protocol', 'province',
  'provision', 'publication', 'publicity', 'pulse', 'pump', 'punch', 'punishment',
  'puppet', 'purchase', 'purity', 'pursuit', 'puzzle', 'pyramid', 'qualification',
  'quarrel', 'quarter', 'quest', 'quota', 'quotation', 'race', 'racism',
  'rack', 'radar', 'radiation', 'rage', 'raid', 'rail', 'rally', 'ranch',
  'range', 'ranking', 'rape', 'rate', 'rating', 'ray', 'readiness', 'realization',
  'realm', 'rear', 'rebellion', 'recession', 'reckoning', 'recourse',
  'recruitment', 'refuge', 'refugee', 'refusal', 'regime', 'registration',
  'regret', 'regulation', 'rehabilitation', 'reign', 'rejection', 'relief',
  'reliance', 'remainder', 'remark', 'remedy', 'remnant', 'renaissance',
  'renewal', 'rent', 'repetition', 'representation', 'reproduction', 'rescue',
  'resemblance', 'reservation', 'residence', 'residue', 'resignation',
  'resistance', 'resort', 'restoration', 'restraint', 'restriction', 'retail',
  'retreat', 'revelation', 'revenge', 'review', 'revival', 'reward', 'rhythm',
  'ribbon', 'riddle', 'rifle', 'right', 'riot', 'risk', 'rite', 'ritual',
  'rival', 'robbery', 'robot', 'rod', 'romance', 'rope', 'rough', 'routine',
  'royalty', 'ruin', 'rumor', 'sacrifice', 'saint', 'sake', 'salary', 'sale',
  'salmon', 'salon', 'sanction', 'sanctuary', 'satellite', 'satisfaction',
  'sauce', 'scale', 'scandal', 'scenario', 'scholar', 'scholarship', 'scissors',
  'scope', 'scratch', 'scream', 'script', 'sculpture', 'seal', 'search',
  'sector', 'seed', 'segment', 'self', 'seminar', 'senate', 'sensation',
  'sensitivity', 'sentiment', 'separation', 'sequence', 'sergeant', 'setback',
  'settlement', 'sewer', 'shade', 'shadow', 'shaft', 'shame', 'shark', 'shed',
  'sheet', 'shelf', 'shell', 'shelter', 'sheriff', 'shield', 'shift', 'shipping',
  'shock', 'shore', 'shortage', 'shortly', 'shrine', 'shrug', 'sibling', 'sigh',
  'sight', 'signal', 'significance', 'silence', 'silk', 'simplicity', 'sin',
  'sketch', 'ski', 'skull', 'slam', 'slave', 'slice', 'slide', 'slogan',
  'slope', 'slot', 'smell', 'smile', 'snap', 'socket', 'soldier', 'sole',
  'solicitor', 'solidarity', 'solitude', 'solution', 'sorrow', 'soul',
  'sovereignty', 'span', 'specialist', 'specimen', 'spectacle', 'spectrum',
  'speculation', 'sphere', 'spice', 'spine', 'spite', 'split', 'spokesman',
  'sponsor', 'spot', 'spray', 'squad', 'stack', 'stadium', 'staff', 'stain',
  'staircase', 'stake', 'stall', 'stance', 'standard', 'standpoint', 'statue',
  'statute', 'steam', 'steel', 'steward', 'stimulus', 'stomach', 'stool',
  'storage', 'strain', 'strand', 'strap', 'straw', 'stream', 'stretch',
  'stride', 'strike', 'strip', 'stroke', 'struggle', 'stunt', 'submarine',
  'submission', 'subsidy', 'substance', 'substitute', 'suburb', 'succession',
  'suffering', 'suite', 'suitor', 'summit', 'superintendent', 'superiority',
  'superstition', 'supplement', 'supporter', 'suppression', 'surface', 'surge',
  'surgeon', 'surname', 'surplus', 'surrender', 'surrounding', 'survey',
  'survival', 'survivor', 'suspect', 'suspension', 'suspicion', 'sweater',
  'sweep', 'swing', 'switch', 'sword', 'symbol', 'symptom', 'syndrome',
  'synthesis', 'tactic', 'tail', 'tank', 'tap', 'target', 'tariff', 'taste',
  'taxi', 'technique', 'teenager', 'telephone', 'telescope', 'temple',
  'temptation', 'tenant', 'tendency', 'tent', 'tenure', 'terrace', 'territory',
  'terror', 'testament', 'testimony', 'text', 'texture', 'theater', 'theft',
  'theme', 'theologian', 'therapist', 'thief', 'throne', 'thumb', 'thunder',
  'tide', 'tile', 'timber', 'tissue', 'tobacco', 'tolerance', 'tomb', 'ton',
  'tone', 'tournament', 'towel', 'tower', 'toxin', 'trace', 'track',
  'trademark', 'tragedy', 'trail', 'trait', 'transaction', 'transcript',
  'transformation', 'transition', 'translation', 'transmission', 'transparency',
  'transport', 'trap', 'trash', 'tray', 'treasure', 'treaty', 'trek', 'trial',
  'tribe', 'tribute', 'triumph', 'troop', 'trophy', 'trunk', 'tube', 'tuition',
  'tumor', 'tunnel', 'turbine', 'tutor', 'twilight', 'twist', 'tyranny',
  'undergraduate', 'undertaking', 'unemployment', 'uniform', 'unity', 'universe',
  'update', 'upgrade', 'uprising', 'utility', 'vacation', 'vaccine', 'vacuum',
  'validity', 'vapor', 'venture', 'venue', 'verdict', 'vessel', 'veteran',
  'victory', 'viewpoint', 'villager', 'vinegar', 'violation', 'violence',
  'virtue', 'vision', 'visitor', 'vitamin', 'vocabulary', 'volcano', 'volunteer',
  'vote', 'voyage', 'wage', 'wagon', 'waist', 'wallet', 'wardrobe', 'warehouse',
  'warfare', 'warmth', 'warrant', 'warrior', 'waste', 'watchdog', 'weapon',
  'weave', 'weed', 'weekend', 'welfare', 'well', 'whale', 'wheat', 'wheel',
  'whip', 'whisper', 'wickedness', 'wilderness', 'willingness', 'witness', 'wolf',
  'wonder', 'wool', 'wording', 'workshop', 'worm', 'worship', 'wound', 'wrap',
  'wreck', 'wrist', 'yell', 'yield', 'zone', 'zoo',
];
