/** 400 common English nouns for the Random Noun Generator */
export const NOUN_LIST: string[] = [
  'ability', 'accident', 'account', 'action', 'activity', 'actor', 'addition',
  'address', 'advantage', 'advice', 'afternoon', 'age', 'agency', 'agreement',
  'air', 'airplane', 'airport', 'alarm', 'alcohol', 'ambition', 'amount',
  'analyst', 'anger', 'animal', 'answer', 'apartment', 'apple', 'application',
  'area', 'argument', 'arm', 'army', 'arrival', 'art', 'article', 'artist',
  'aspect', 'assignment', 'assistant', 'association', 'atmosphere', 'attack',
  'attention', 'attitude', 'audience', 'aunt', 'author', 'average', 'award',
  'baby', 'back', 'bag', 'balance', 'ball', 'banana', 'band', 'bank', 'bar',
  'baseball', 'basis', 'basket', 'bath', 'bathroom', 'battle', 'beach', 'bear',
  'beauty', 'bed', 'bedroom', 'beer', 'beginning', 'behavior', 'benefit', 'bike',
  'bill', 'bird', 'birthday', 'bit', 'blood', 'board', 'boat', 'body', 'bone',
  'book', 'border', 'boss', 'bottle', 'bottom', 'box', 'boy', 'boyfriend',
  'brain', 'branch', 'bread', 'breakfast', 'breath', 'bridge', 'brother',
  'budget', 'building', 'bus', 'business', 'butter', 'button', 'cabinet',
  'camera', 'campaign', 'candle', 'captain', 'car', 'card', 'career', 'carpet',
  'case', 'cash', 'cat', 'category', 'cause', 'celebration', 'cell', 'chair',
  'champion', 'chance', 'chapter', 'charity', 'cheese', 'chemistry', 'chest',
  'chicken', 'child', 'chocolate', 'choice', 'church', 'cigarette', 'city',
  'class', 'classroom', 'client', 'climate', 'clock', 'clothes', 'cloud', 'club',
  'coast', 'coffee', 'college', 'combination', 'committee', 'communication',
  'community', 'company', 'comparison', 'competition', 'complaint', 'computer',
  'concept', 'concern', 'conclusion', 'condition', 'confusion', 'connection',
  'consequence', 'context', 'contract', 'contribution', 'control',
  'conversation', 'cookie', 'copy', 'corner', 'cost', 'country', 'county',
  'courage', 'course', 'cousin', 'cow', 'cream', 'criticism', 'culture', 'cup',
  'currency', 'customer', 'dad', 'danger', 'data', 'database', 'daughter',
  'day', 'death', 'debate', 'debt', 'decision', 'definition', 'delivery',
  'demand', 'department', 'departure', 'description', 'design', 'desk', 'detail',
  'development', 'device', 'diamond', 'dinner', 'direction', 'director',
  'dirt', 'disaster', 'discipline', 'discussion', 'disease', 'disk', 'display',
  'distance', 'distribution', 'doctor', 'document', 'dog', 'door', 'drama',
  'drawer', 'drawing', 'dream', 'dress', 'drink', 'driver', 'ear', 'earth',
  'economics', 'economy', 'editor', 'education', 'effect', 'effort', 'egg',
  'election', 'elevator', 'emotion', 'employee', 'employer', 'end', 'energy',
  'engine', 'engineer', 'entertainment', 'enthusiasm', 'entry', 'environment',
  'error', 'estate', 'evening', 'event', 'exam', 'examination', 'example',
  'exchange', 'excitement', 'excuse', 'exercise', 'experience', 'expert',
  'explanation', 'expression', 'extension', 'eye', 'face', 'fact', 'failure',
  'family', 'farmer', 'father', 'feature', 'feedback', 'field', 'figure',
  'film', 'finger', 'fire', 'fish', 'flight', 'flower', 'food', 'foot',
  'football', 'force', 'forest', 'form', 'fortune', 'foundation', 'friend',
  'fruit', 'funeral', 'future', 'game', 'garden', 'gate', 'gene', 'girl',
  'girlfriend', 'glass', 'goal', 'god', 'gold', 'golf', 'government',
  'grandmother', 'grass', 'grocery', 'group', 'growth', 'guest', 'guidance',
  'guitar', 'gun', 'hair', 'hall', 'hand', 'hat', 'head', 'health', 'heart',
  'height', 'highway', 'hill', 'history', 'home', 'homework', 'honey', 'hope',
  'horse', 'hospital', 'hotel', 'house', 'housing', 'idea', 'image',
  'imagination', 'impact', 'importance', 'impression', 'improvement', 'income',
  'independence', 'indication', 'industry', 'information', 'insect', 'insight',
  'inspector', 'instruction', 'insurance', 'intention', 'interaction',
  'interest', 'internet', 'introduction', 'investment', 'island', 'issue',
  'item', 'jacket', 'job', 'judge', 'judgment', 'juice', 'key', 'king',
  'kitchen', 'knowledge', 'lab', 'ladder', 'lady', 'lake', 'language', 'law',
  'leader', 'league', 'leather', 'letter', 'library', 'life', 'light',
  'lip', 'list', 'literature', 'location', 'loss', 'love', 'luck', 'lunch',
  'machine', 'magazine', 'mail', 'mall', 'man', 'management', 'manager', 'map',
  'market', 'marriage', 'math', 'meal', 'meaning', 'measurement', 'meat',
  'media', 'medicine', 'medium', 'member', 'memory', 'menu', 'message', 'metal',
  'method', 'midnight', 'milk', 'mind', 'mixture', 'mode', 'mom', 'moment',
  'money', 'monitor', 'month', 'mood', 'morning', 'mother', 'mountain', 'mouse',
  'mouth', 'movie', 'mud', 'muscle', 'museum', 'music', 'name', 'nation',
  'nature', 'neck', 'negotiation', 'network', 'news', 'newspaper', 'night',
  'noise', 'nose', 'note', 'number', 'nurse', 'object', 'obligation', 'office',
  'oil', 'operation', 'opinion', 'opportunity', 'orange', 'order',
  'organization', 'outcome', 'oven', 'owner', 'pain', 'painting', 'paper',
  'parent', 'park', 'parking', 'part', 'party', 'passenger', 'passion',
  'patience', 'pattern', 'payment', 'penalty', 'pencil', 'people', 'percentage',
  'performance', 'period', 'permission', 'person', 'personality', 'perspective',
  'philosophy', 'phone', 'photo', 'physics', 'piano', 'picture', 'pie', 'place',
  'plan', 'plane', 'planet', 'plant', 'plastic', 'platform', 'player', 'poem',
  'poet', 'police', 'policy', 'politics', 'pollution', 'population', 'position',
  'possession', 'possibility', 'potato', 'power', 'practice', 'preference',
  'preparation', 'president', 'pressure', 'price', 'priority', 'problem',
  'procedure', 'process', 'product', 'profession', 'professor', 'profit',
  'program', 'promotion', 'property', 'proposal', 'protection', 'psychology',
  'purpose', 'quality', 'quantity', 'queen', 'question', 'radio', 'rain',
  'ratio', 'reaction', 'reality', 'reason', 'reception', 'recipe', 'recognition',
  'recommendation', 'record', 'reflection', 'region', 'relation', 'relationship',
  'religion', 'replacement', 'report', 'republic', 'reputation', 'request',
  'research', 'resolution', 'resource', 'response', 'responsibility', 'restaurant',
  'result', 'revenue', 'revolution', 'rice', 'river', 'road', 'rock', 'role',
  'room', 'rule', 'safety', 'salad', 'salt', 'sample', 'sandwich', 'scene',
  'schedule', 'school', 'science', 'screen', 'sea', 'season', 'secretary',
  'section', 'security', 'selection', 'sense', 'series', 'service', 'session',
  'shape', 'shirt', 'shoe', 'shop', 'side', 'sign', 'signature', 'silver',
  'singer', 'sir', 'sister', 'site', 'situation', 'skill', 'skin', 'sky',
  'snow', 'society', 'software', 'soil', 'son', 'song', 'sort', 'soup',
  'source', 'space', 'speech', 'spirit', 'sport', 'spring', 'star', 'state',
  'statement', 'steak', 'step', 'stock', 'stomach', 'store', 'storm', 'story',
  'stranger', 'strategy', 'street', 'stress', 'structure', 'student', 'studio',
  'style', 'subject', 'success', 'suggestion', 'summer', 'sun', 'supermarket',
  'surgery', 'surprise', 'sweetheart', 'swimming', 'sympathy', 'system',
  'table', 'tale', 'task', 'tax', 'tea', 'teacher', 'team', 'tear',
  'technology', 'television', 'temperature', 'tennis', 'tension', 'term',
  'test', 'thanks', 'theory', 'thing', 'thought', 'throat', 'ticket', 'time',
  'tongue', 'tool', 'tooth', 'topic', 'tour', 'town', 'tradition', 'trainer',
  'transportation', 'tree', 'trip', 'trouble', 'truck', 'trust', 'truth', 'tune',
  'uncle', 'understanding', 'union', 'unit', 'university', 'user', 'valley',
  'value', 'variation', 'vehicle', 'version', 'video', 'view', 'village',
  'virus', 'voice', 'volume', 'wall', 'war', 'warning', 'water', 'wave', 'way',
  'weakness', 'wealth', 'weather', 'web', 'wedding', 'week', 'weight', 'wife',
  'wind', 'window', 'wine', 'winter', 'wish', 'woman', 'wood', 'word', 'work',
  'worker', 'world', 'writer', 'yard', 'year', 'youth',
];
