/**
 * 500 human-written sentences for the Random Sentence Generator.
 *
 * Decision: After competitive analysis, we rejected template-based generation.
 * randomwordgenerator.com (SERP #2) explicitly tried computer-generated sentences
 * and "found the results to be disappointing." textfixer.com's template approach
 * produces visible grammar bugs. We follow the validated approach: manually
 * written sentences organized by use case.
 *
 * Categories:
 *   Story starters (40%, 200) — novel/story opening lines that hook
 *   Absurd situations (25%, 125) — funny, quirky, surreal
 *   Dialogue openers (20%, 100) — conversation starters
 *   Mystery hooks (15%, 75) — intriguing, strange, compelling
 */

export const PREWRITTEN_SENTENCES: string[] = [
  // ============================================================
  // STORY STARTERS (200) — opening lines that make you ask "then what?"
  // ============================================================

  // Character-focused (50)
  "Her grandmother had always warned her about the woods behind the house, but she'd never said why.",
  "He wasn't the kind of person who believed in coincidences, but three times in one week was hard to ignore.",
  "The thing about being invisible, she'd learned, was that people told you their secrets without realizing it.",
  "Maya had never been late to anything in her life, so when she didn't show up, everyone knew something was wrong.",
  "My father left me a key and a note that said 'use it only once' — that was twelve years ago.",
  "She could remember every conversation she'd ever had, every word, every pause, every lie.",
  "The new kid in town didn't speak for the first three weeks, and when he finally did, everyone understood why.",
  "His grandfather had been a watchmaker, and he'd always said that time wasn't what people thought it was.",
  "No one believed Clara when she said she could hear colors, until the day she painted the sound of a scream.",
  "He had the kind of face that made you want to trust him, which was exactly why you shouldn't.",
  "The librarian knew every book in the building, but there was one she'd never opened.",
  "After the accident, Leo discovered that he could see three minutes into the future — and that it was never enough.",
  "Her voice could calm any storm, which made it ironic that she caused so many.",
  "He'd spent thirty years as a doorman at a hotel where nothing ever happened, until the night everything did.",
  "Aisha had prepared for every possible outcome except the one where they told her yes.",
  "The old woman at the bus stop had been sitting there every day for forty years, and she'd never once gotten on a bus.",
  "When the detective asked him where he'd been, he smiled and said he'd been nowhere at all.",
  "She wore gloves every single day, not because her hands were ugly, but because they were the most beautiful thing anyone had ever seen.",
  "Nobody knew the janitor's name, but he knew everyone else's — and he knew which ones had secrets.",
  "He only took photographs of empty rooms, and every single one of them felt occupied.",
  "The thing about having a perfect memory is that you can never forgive anyone, least of all yourself.",
  "She'd been running for so long she couldn't remember what she was running from, only that stopping felt like death.",
  "Marcus had a gift for finding lost things, but he'd never found what he was really looking for.",
  "The old fisherman told stories that changed every time he told them, and somehow every version was true.",
  "She became a locksmith because she believed every locked door was just a question waiting to be answered.",
  "His last words before disappearing were 'I finally understand,' and no one had ever figured out what he meant.",
  "The boy who lived above the bakery could tell you exactly what kind of day you'd had just by the bread you bought.",
  "She measured her life in cups of coffee and books she'd never finish, and she was perfectly fine with that.",
  "He was the kind of tired that sleep couldn't fix, the kind that came from carrying a secret for too long.",
  "The woman on the third floor never opened her curtains, but every morning at seven, a different song played through her door.",
  "She'd built a career out of noticing things other people missed, which is how she knew her husband was a stranger.",
  "The youngest of seven children, Noah learned early that the only way to be heard was to say something worth listening to.",
  "She kept a list of everyone who had wronged her, not for revenge, but because she was terrified of forgetting.",
  "He had taught himself to read at four, to code at eight, and to lie at twelve — only the last one ever came naturally.",
  "The tattoo on her wrist was a map to somewhere she'd never been, drawn by someone she'd never met.",
  "He collected umbrellas left behind on trains, and each one had a story that wasn't his.",
  "She could tell when someone was about to leave her, which meant she spent most of her life bracing for impact.",
  "The man in apartment 4B received mail for seventeen different names, and he answered to all of them.",
  "She'd learned to cook from her grandmother, to fight from her mother, and to forgive from absolutely no one.",
  "He wasn't afraid of dying — he was afraid of dying without anyone noticing he'd been alive.",
  "The watchmaker's daughter had never once looked at a clock without feeling like it was looking back.",
  "She liked to sit in hotel lobbies and imagine the lives of strangers, which was safer than examining her own.",
  "He had been a translator during the war, and he still couldn't decide if words had saved more lives than they'd taken.",
  "The only thing scarier than what she'd seen in the basement was the fact that no one else could see it.",
  "He'd been a magician before he became a therapist, and he said the skills were remarkably similar.",
  "The postman had walked the same route for twenty-two years, and he could tell when someone was home just by the silence.",
  "She never made promises she couldn't keep, which was why she'd only made three in her entire life.",
  "The gardener said every plant had a personality, and he seemed to get along better with the difficult ones.",
  "She kept every birthday card she'd ever received, not because she was sentimental, but because she was collecting handwriting samples.",
  "His mother always said he had too much imagination — she meant it as a warning, he took it as a compliment.",

  // Setting-based (50)
  "The city looked different from the rooftop at 4 AM — quieter, almost peaceful, like it was holding its breath.",
  "The house at the end of the lane had been empty for years, but the garden was always perfectly tended.",
  "The island didn't appear on any map, and the people who lived there preferred it that way.",
  "The diner was open 24 hours, and at 3 AM it served more secrets than coffee.",
  "The forest behind the school was older than the town, older than the country, older than memory.",
  "The library had a room on the third floor that wasn't in the blueprints, and the librarian refused to discuss it.",
  "In a town this small, the arrival of a stranger was either a blessing or a threat, and no one could agree which this one was.",
  "The train station had been closed since 1973, but every night at midnight, the platform lights flickered on.",
  "The hotel had 100 rooms, but the front desk only ever booked 99 of them.",
  "The bridge connecting the two halves of the city was said to be unbreakable, until the morning it wasn't.",
  "The old theater on Main Street still showed movies every Friday, but no one remembered buying tickets.",
  "The lighthouse keeper had been dead for a decade, yet the light still came on every night at sunset.",
  "The carnival arrived without warning and left without saying goodbye, and the town was never quite the same.",
  "The clock tower hadn't chimed in fifty years, but the old folks still looked up at it every hour.",
  "The village at the bottom of the lake was visible only during droughts, and this summer had been very, very dry.",
  "The coffee shop on the corner had free Wi-Fi, terrible lighting, and a basement that wasn't on the floor plan.",
  "The mountain in the distance had no name, because anyone who climbed it never came back to name it.",
  "The alley between the bookstore and the bakery was precisely wide enough for two people to pass, and precisely dark enough to hide.",
  "The garden behind the abandoned church bloomed in winter, and no one had ever planted anything there.",
  "The hospital's east wing had been closed for renovations since 1987, but the lights still worked.",
  "The pier stretched so far into the ocean that on foggy days you couldn't see where it ended.",
  "The museum's newest exhibit was a room with nothing in it, and it drew the biggest crowds.",
  "The well in the center of town had been dry for generations, but children still whispered wishes into it.",
  "The parking garage on Seventh Street had thirteen levels, and the elevator would only take you to twelve.",
  "The market appeared every Sunday at dawn and vanished by noon, along with anyone still inside.",
  "The highway stretched endlessly through the desert, and every few miles there was a phone booth with no phone.",
  "The cabin by the lake had been in the family for a century, and not a single family member had ever spent the night there.",
  "The warehouse district was silent during the day but vibrated with music every night, from a source no one could locate.",
  "The chapel on the hill conducted services in a language that only three living people understood.",
  "The boardwalk was empty in February, which was exactly why she came then — the silence was medicinal.",
  "The public pool had been drained for twenty years, but the smell of chlorine still lingered on hot days.",
  "The observatory had been abandoned for decades, but the telescope still pointed at the same patch of sky.",
  "The stairwell went down farther than the building's foundation should have allowed.",
  "In this city, the pigeons had learned to use the crosswalks, and no one had bothered to question why.",
  "The old general store sold things you couldn't find anywhere else, and the owner never explained where they came from.",
  "The playground was always empty at twilight, and the swings would move even when there was no wind.",
  "The university's oldest building had corridors that shifted subtly between semesters, and only the janitors noticed.",
  "The lighthouse was automated now, but the old keeper still visited every day to talk to the light.",
  "The greenhouse at the edge of town grew plants that didn't exist in any botanical database.",
  "The cemetery's oldest section had gravestones with dates that didn't add up, and no one talked about why.",
  "The abandoned subway station had mosaic tiles depicting a future that looked nothing like what actually happened.",
  "The bakery opened at 5 AM and always sold out by 6, but no one had ever seen a customer come or go.",
  "The fountain in the square stopped working the day the mayor disappeared, and the water had been still ever since.",
  "The radio tower on the hill had been transmitting the same signal since 1962, and no one knew what it meant.",
  "The drive-in theater showed movies from a decade that hadn't happened yet, and the audience never seemed to mind.",
  "The old fire station had a pole that went up instead of down, and the firefighters treated this as perfectly normal.",
  "The border between the two countries was marked by a river that flowed in both directions at once.",
  "The clock repair shop's window display hadn't changed in forty years, but the time shown was always current.",
  "The prison had been converted into luxury apartments, but the residents said the cells still felt like cells at night.",
  "The bridge only appeared in photographs — anyone who tried to find it in person found nothing but water.",

  // Action-based (50)
  "He pressed the button without knowing what it did, which pretty much summed up his entire approach to life.",
  "She ran until her lungs burned and her legs gave out, and only then did she realize she wasn't being chased.",
  "He opened the letter with trembling hands, read it twice, and then did the most dangerous thing imaginable — he believed it.",
  "The jump was farther than she'd estimated, and halfway across she realized this might be the last mistake she'd ever make.",
  "He picked the lock in under thirty seconds, which was about twenty-eight seconds faster than he should have been able to.",
  "She dialed the number she'd sworn she would never call, and it rang exactly once before someone answered.",
  "He threw the package into the river and watched it sink, not knowing it would float back up three days later.",
  "She packed a single bag, took all the cash from the drawer, and left without looking back at the house she'd lived in for twenty years.",
  "He signed the contract without reading the fine print, which turned out to be the best mistake of his entire career.",
  "She deleted the message before finishing it, but the damage was already done — the words existed now, even if only in her mind.",
  "He stepped off the curb at exactly the wrong moment, and the next thing he knew, everything was different.",
  "She pressed send before she could talk herself out of it, and then stared at the screen for three hours waiting for a reply.",
  "He found the photograph tucked inside a library book, and the person in it had been dead for ten years.",
  "She smashed the vase against the wall, not out of anger but because she'd seen something move inside it.",
  "He drove past the same gas station three times before admitting he was lost, and by then it was too late to turn back.",
  "She climbed the fence, tore her jacket, and landed in a garden that didn't seem to belong to this century.",
  "He burned the letter immediately after reading it, but the words had already seared themselves into his memory.",
  "She followed the sound of music through the empty building, floor after floor, until she found the source — and wished she hadn't.",
  "He closed his eyes for what felt like a second, and when he opened them, three days had passed.",
  "She caught the falling glass before it hit the ground, which was when she realized her reflexes weren't normal anymore.",
  "He dug the hole deeper than necessary, telling himself it was for the tree, but knowing it was for something else entirely.",
  "She turned the key in a lock that hadn't been opened in thirty years, and the door swung inward without a sound.",
  "He memorized the combination and then destroyed the paper, which meant he was now the only person in the world who knew.",
  "She gave away everything she owned, piece by piece, until all that was left was a single photograph and a question.",
  "He walked into the police station and confessed to a crime that hadn't been committed yet.",
  "She cut her hair in the middle of the night, and when she looked in the mirror, she saw someone she'd been trying to become.",
  "He recorded the conversation without the other person knowing, and then spent the next year trying to forget what he'd heard.",
  "She untied the boat and let it drift, not caring where it went as long as it was away from here.",
  "He broke the rules on purpose, for once, and discovered that rules were just suggestions that enough people had agreed to follow.",
  "She painted over the mural she'd spent six months creating, because sometimes destruction was the point.",
  "He waited at the rendezvous point for three hours past the agreed time, and just as he was about to leave, a child handed him a note.",
  "She crossed the street without looking, and the car that swerved to avoid her crashed into a fire hydrant — changing three lives in an instant.",
  "He buried the box in the backyard under the full moon, and the next morning the ground was undisturbed.",
  "She quit her job via a Post-it note that said only 'I've found something better,' and no one ever found out what it was.",
  "He boarded the wrong train intentionally, curious to see where it would take him, and three countries later, he still hadn't gone back.",
  "She whispered the secret into the well and heard it echo back in a voice that wasn't hers.",
  "He jumped into the water to save someone who wasn't drowning, and in doing so, nearly drowned himself.",
  "She lit the candle that was only supposed to be lit in emergencies, and then waited to see what kind of emergency would arrive.",
  "He took the long way home deliberately, which was how he noticed the car that had been following him for miles.",
  "She folded the map wrong and discovered a place that wasn't supposed to exist between page fourteen and page fifteen.",
  "He opened the door without knocking, and what he saw made him close it again immediately — not from fear, but from respect.",
  "She sold the ring her grandmother had given her, and the buyer asked if she knew what she'd actually been wearing all these years.",
  "He counted the steps from his apartment to the park every morning, and the day the number changed, he knew something was off.",
  "She erased the hard drive the night before the presentation, and her boss never found out it was on purpose.",
  "He planted the seeds in alphabetical order by their Latin names, which was ridiculous, but the resulting garden was magnificent.",
  "She froze when she heard the footsteps behind her, then realized they were her own, echoing off walls she couldn't see.",
  "He accepted the dare without asking what it was, a habit that had cost him two teeth and a marriage.",
  "She rewrote her will every year on her birthday, not because her assets changed, but because her grudges did.",
  "He yelled at the top of his lungs in the middle of an empty field, and something in the distance yelled back.",
  "She logged out of every account, deleted every photo, and started a life where no one knew who she'd been — and it was glorious.",

  // Emotion/reflection-based (50)
  "The worst part wasn't the lie itself — it was how easily it had slipped out.",
  "She'd spent so long pretending to be strong that she'd forgotten how to be anything else.",
  "Forgiveness wasn't something he was good at, which was funny, because he'd been asking for it his whole life.",
  "The thing about hitting rock bottom is that it's solid ground, and from there, the only direction is up.",
  "She finally understood why her mother had always looked tired — and it wasn't the kind of tired that sleep could fix.",
  "He realized, at forty-two, that he'd built a life around what he was supposed to want, not what he actually wanted.",
  "The silence between them had grown so large that neither of them could shout across it anymore.",
  "She always said yes because saying no felt like closing a door she might need to walk through someday.",
  "He'd spent decades becoming someone his younger self would have despised, and only recently had he started to wonder who was right.",
  "The grief didn't get smaller over time — she just got bigger around it, like a tree growing around a fencepost.",
  "He'd learned to apologize so well that people often thanked him for forgiving them, which wasn't the same thing at all.",
  "The loneliness came in waves, and she'd learned to surf most of them, but some still pulled her under.",
  "She measured happiness in small things — a warm cup, a kind word, a door that opened when she knocked.",
  "He wasn't afraid of failure; he was afraid of succeeding and finding out it didn't feel any different.",
  "The bravest thing she ever did was admit that she needed help, and the second bravest was accepting it.",
  "He had spent so long being angry that he'd forgotten what he was angry about in the first place.",
  "She never cried in front of people, not because she was strong, but because she was afraid that once she started, she'd never stop.",
  "He realized that the version of himself he'd been trying to fix wasn't broken — just different, which was not the same thing.",
  "She kept waiting for someone to give her permission to live the life she wanted, until she realized no one was going to.",
  "The most difficult thing he'd ever done was stay, when every cell in his body was screaming at him to run.",
  "She'd been chasing closure like it was a destination, when really it was just a decision she'd been refusing to make.",
  "He found that the opposite of love wasn't hate — it was indifference, which he'd been practicing for years without knowing its name.",
  "She'd built walls so high she couldn't see over them anymore, and she wasn't sure if that was safety or prison.",
  "He always arrived early because somewhere deep down he believed that if he was on time, no one would wait for him.",
  "She learned that home wasn't a place, but it also wasn't a person — it was the feeling of not having to explain yourself.",
  "The kindness of strangers had saved him more times than he could count, which is why he always tipped well.",
  "She'd been the villain in someone else's story without ever knowing it, and that bothered her more than she wanted to admit.",
  "He carried guilt like a family heirloom — heavy, unwieldy, and impossible to get rid of without feeling like he'd betrayed someone.",
  "She realized she'd outgrown her own life the way a hermit crab outgrows its shell, and the search for a new one was terrifying.",
  "The greatest gift anyone ever gave him was telling him the truth when a lie would have been so much easier.",
  "She stopped waiting for an apology that was never coming, and in doing so, set them both free.",
  "He'd been running on empty for so long that he'd convinced himself the warning light was just part of the dashboard.",
  "She loved the rain because it was the only time the world seemed to slow down enough for her to catch up.",
  "He finally understood that being right and being happy were sometimes mutually exclusive choices.",
  "She collected moments of joy like other people collected stamps, pressing them carefully into the album of her memory.",
  "The hardest habit to break was hoping — not for anything specific, just the generic, reflexive hope that things would be different tomorrow.",
  "He discovered that self-respect wasn't something you found; it was something you built, one brick of a boundary at a time.",
  "She'd been so busy being grateful for what she had that she'd forgotten she was allowed to want more.",
  "He realized that the voice in his head that sounded like his father was just fear wearing a familiar face.",
  "The best advice she ever received was 'you don't have to attend every argument you're invited to.'",
  "He stopped checking his phone every five minutes and discovered that the world didn't end — but his anxiety had been running the show for years.",
  "She apologized for things that weren't her fault because she'd been taught that peace was more important than truth.",
  "He finally learned to say no without explaining himself, and it felt like taking off a backpack full of rocks.",
  "She realized that growing up wasn't about having answers — it was about being comfortable with better questions.",
  "The moment he stopped trying to be interesting was the moment he actually became interesting.",
  "She'd been treating her life like a rough draft, always planning to rewrite it later, until she realized this was the final copy.",
  "He found that the people who mattered most were the ones who showed up not when things were good, but when showing up was hard.",
  "She decided that if she was going to be too much for some people, those people could go find less.",
  "He learned that courage wasn't the absence of fear — it was being afraid and doing the thing anyway, preferably before breakfast.",
  "The last thing she expected was to find herself in the middle of nowhere, which was exactly where she needed to be.",

  // ============================================================
  // ABSURD SITUATIONS (125) — funny, quirky, surreal
  // ============================================================

  // Animal absurdity (30)
  "The pigeon looked me dead in the eye and said, 'You didn't see anything.'",
  "My cat has been staring at the same corner of the ceiling for three months, and I'm starting to think it knows something.",
  "The dog had learned to open the refrigerator, which was impressive until we realized he was cooking for someone.",
  "A raccoon in a tiny business suit boarded the subway at 42nd Street, and no one reacted because this was, apparently, normal now.",
  "The parrot at the zoo had learned to mimic the security guard's radio, and chaos had been unfolding for weeks.",
  "The goose didn't just chase people — it maintained a spreadsheet of grievances dating back to 2019.",
  "My goldfish has been giving me suspicious looks ever since I switched to a cheaper brand of fish food.",
  "The squirrels in the park have organized, and frankly, their demands are reasonable.",
  "A llama escaped from a petting zoo and somehow ended up as the unofficial mayor of a small town in Oregon.",
  "The cat brought home a receipt instead of a dead mouse, and I'm not sure which is more concerning.",
  "Every crow in the neighborhood follows the same person to work, and biologists are baffled but the crows seem very sure about it.",
  "My neighbor's dog barks exclusively at Tuesdays, and I've started to dread the middle of the week.",
  "The aquarium octopus has been rearranging its tank decorations to spell out rude words in Morse code.",
  "A seagull stole my sandwich and left a perfectly good ten-dollar bill in its place, and I have so many questions.",
  "The local deer have figured out how to use the crosswalk, which is adorable but also slightly terrifying.",
  "My hamster escaped and was found three days later running a successful underground treat-smuggling operation.",
  "The penguins at the zoo have developed what can only be described as a mafia hierarchy.",
  "A dolphin at the research center has learned to mimic human laughter, and it only does it when someone makes a mistake.",
  "My rabbit has more Instagram followers than I do, and honestly, I understand why.",
  "The neighborhood cats hold a meeting every Thursday at midnight, and my cat came back with minutes and action items.",
  "An owl has taken up residence outside my window and hoots exclusively to the rhythm of eighties pop songs.",
  "The horse seemed perfectly normal until it started responding to emails that no one had sent.",
  "A fox keeps leaving neat little packages of berries on my porch, and I don't know if it's a gift or a warning.",
  "My dog barks at the front door whenever there's no one there, and I've started introducing myself to the empty air just in case.",
  "The zoo's sloth escaped two weeks ago and has only made it about twelve feet from the enclosure.",
  "A flock of pigeons has been following the same Uber Eats driver for months, and scientists call it 'opportunistic symbiosis.'",
  "My snake hasn't moved in a week, which I thought meant it was dead, but it turns out it was just deeply unimpressed with my life choices.",
  "The ants in my kitchen have established a trade route that I've accidentally disrupted twice, and the diplomatic consequences have been severe.",
  "A bear broke into a cabin and left a Yelp review complaining about the lack of honey.",
  "My pet turtle, who moves approximately never, somehow ended up in the neighbor's pool, and I have theories but no evidence.",

  // Object absurdity (30)
  "The vending machine took my dollar and gave me a receipt for one 'existential crisis' instead of chips.",
  "My toaster has started burning messages into the bread, and they're getting increasingly personal.",
  "The GPS navigation voice has started questioning my life choices instead of giving directions.",
  "My refrigerator sent me a text asking if I was ever going to eat the leftovers from March — it had a point.",
  "The printer jammed and instead of paper, it spat out what appears to be a detailed map of somewhere that doesn't exist.",
  "My coffee maker has started brewing different strengths based on what it thinks I need, and it's never wrong.",
  "The elevator has been stopping at a floor that doesn't have a button, and I've decided not to investigate.",
  "My phone's autocorrect has been replacing my text messages with fragments of what I can only describe as poetry.",
  "The ceiling fan has developed a rhythm that perfectly syncs with the soundtrack of my worst decisions.",
  "My laptop camera light turns on at exactly 3:04 AM every night, and the footage always shows an empty room.",
  "The automatic doors at the grocery store don't open for me anymore, and I'm trying not to take it personally.",
  "My alarm clock has stopped beeping and started whispering my name instead, which is somehow worse.",
  "The Roomba has been deliberately bumping into the same chair leg for six months, and I respect the commitment.",
  "My microwave displays the time in Roman numerals now, and I didn't change any settings — it just decided this was superior.",
  "The shower has started playing smooth jazz whenever I'm running late, which feels passive-aggressive.",
  "My car's check engine light has been on so long that the mechanic now refers to it as 'part of the car's personality.'",
  "The thermostat has been adjusted by someone who isn't me, and the settings suggest a preference for tropical rainforest.",
  "My washing machine ate one sock from every pair and then printed a receipt that said 'sacrifice accepted.'",
  "The automatic soap dispenser refuses to acknowledge my existence, but it squirts enthusiastically for my cat.",
  "My headphones have started translating ambient noise into what sounds like a 1940s radio drama.",
  "The self-checkout machine called me by name today, and I've never used a loyalty card in my life.",
  "My blender has opinions about my smoothie recipes, and it communicates them through aggressive pulsing patterns.",
  "The office coffee machine has formed what appears to be a union with the water cooler, and negotiations are tense.",
  "My smart speaker responds to questions I haven't asked yet, which is either very advanced or deeply concerning.",
  "The hotel key card stopped working on the third day, and the front desk said it was because the room had decided I was done.",
  "My stapler has been missing for two weeks, and I found it in the freezer with no explanation from anyone in the household.",
  "The traffic lights on my commute have been turning green just for me, and I don't know who I've impressed to deserve this.",
  "My umbrella has developed opinions about precipitation and refuses to open for what it considers 'insufficient rain.'",
  "The photocopier has been printing duplicates of documents that were never scanned, and the content is unsettling.",
  "My electric toothbrush buzzes in Morse code, and I'm afraid to find out what it's been saying.",

  // Surreal/weird (30)
  "Somewhere in the multiverse, a version of me is being productive right now, and I resent them deeply.",
  "The moon was slightly larger than usual tonight, and only half the population seemed to notice.",
  "Everyone in the city had the same dream last night, and no one has been brave enough to describe it out loud.",
  "The concept of Thursday was invented by a medieval monk who hated weekends and wanted to insert an extra buffer day.",
  "Gravity worked differently on this street — not enough to be dangerous, just enough to make walking feel like a choice.",
  "Colors have been slowly fading from the world, and the only person who noticed is a three-year-old who can't yet explain what's wrong.",
  "The ocean had been trying to communicate with us for centuries, and we'd been interpreting it as weather.",
  "Memory was discovered to be a liquid substance in 2047, which explained why some people leaked theirs everywhere.",
  "Time moved differently in this room — not faster or slower, just with more jazz hands.",
  "The cloud in the shape of a question mark hung over the city for a week, and philosophers declared it a sign they weren't ready to interpret.",
  "Bananas are technically berries, strawberries are technically not, and I'm technically losing my mind over botanical definitions.",
  "If you fold a map enough times, you eventually reach a place that isn't on it — I learned this the hard way.",
  "The sound of one hand clapping was finally recorded in a laboratory, and it sounded exactly like a middle manager's performance review.",
  "Parallel universes were proven to exist when someone's toast landed butter-side up in both realities simultaneously.",
  "The number between three and four had been hiding there all along, but seeing it required a kind of squinting that humans hadn't evolved yet.",
  "The library contained every book that had ever been written plus every book that hadn't, and the overdue fines were astronomical.",
  "Deja vu is just the universe's auto-save feature kicking in, which is comforting until you realize something must have gone wrong.",
  "Mirrors don't actually reflect light — they show you what's on the other side, which is almost the same thing most of the time.",
  "The speed of light is only a limit if you're in a hurry, which the universe decidedly is not.",
  "Your shadow is actually your past self lagging behind by a nanosecond, which means you're literally running from who you used to be.",
  "Silence isn't the absence of sound — it's the presence of all the things that have chosen not to speak.",
  "Every time you forget something, that memory relocates to a parallel version of you who now has one extra thing to remember.",
  "The horizon isn't where the earth ends — it's where your imagination gives up, which is a much sadder boundary.",
  "Tuesday has been scientifically proven to be the longest day, not because of any astronomical factor, but because of pure collective dread.",
  "Consciousness is just the universe's way of experiencing itself, which makes every awkward conversation cosmically significant.",
  "The first person to drink milk from a cow definitely had to explain themselves to the rest of the tribe.",
  "Mathematics was invented by someone who looked at chaos and said 'what if we just made up some rules and pretended they always work.'",
  "The fact that humans can imagine things that don't exist is either our greatest gift or a fundamental glitch in our programming.",
  "Every clock in the world lost exactly one second on the same day, and the official explanation was 'rounding error.'",
  "The most terrifying thing about the universe isn't that it's hostile — it's that it's indifferent, which leaves us free to embarrass ourselves.",

  // Everyday absurd (35)
  "I wasn't sure what was more alarming — that my plants were dying, or that they seemed to be doing it in an organized pattern.",
  "My grocery list somehow ended up in the wrong hands, and now strangers keep buying me the exact things I needed.",
  "I received a jury duty summons addressed to a version of myself from five years ago, and I'm not sure which of us should show up.",
  "The new restaurant in town serves food that tastes exactly like other people's memories, and business is booming.",
  "I accidentally joined a cult that meets in the frozen food aisle, and the initiation involved choosing the right pizza toppings.",
  "My dentist says my teeth are 'philosophically interesting,' which I'm pretty sure is not a compliment.",
  "The waiting room magazine was from 1987, and every article somehow perfectly described my current life situation.",
  "I went to return a library book and discovered I'd been declared legally dead in three different library systems.",
  "My yoga instructor says I breathe like someone who's 'carrying a secret from the 18th century,' and I don't know how to process that.",
  "The Wi-Fi password at the cafe was 'tell me your deepest fear,' and the barista was taking it literally.",
  "I received a package I didn't order containing exactly what I needed but was too afraid to buy myself.",
  "The motivational poster in the break room changed its message overnight, and the new one was unsettlingly specific to my life.",
  "I tried to unsubscribe from a mailing list and ended up on what appears to be a government watchlist for people who click 'unsubscribe' too aggressively.",
  "My horoscope this morning said 'today you will make a decision about cheese,' and I've been paralyzed with anticipation ever since.",
  "The fortune cookie at lunch contained a URL instead of a fortune, and against my better judgment, I visited it.",
  "I signed up for a free trial of adulthood and forgot to cancel before the responsibilities kicked in.",
  "My neighbor has been building something in their garage for six years, and I've seen them bring in a penguin statue, 400 feet of rope, and a trombone.",
  "The annual neighborhood potluck turned into a surprisingly functional local government, and now we have a minister of casserole affairs.",
  "I discovered that my upstairs neighbors are teaching their cat to tap dance, and I've decided to support their artistic journey.",
  "The office plant that everyone has been watering for years turned out to be plastic, and no one knows how to process this betrayal.",
  "I found a USB drive in a parking lot labeled 'ANSWERS,' but it's encrypted with a password that's apparently a riddle I haven't solved yet.",
  "My gym membership auto-renewed for the fifth year, and the staff now greet me by saying 'nice to finally meet you.'",
  "I've been accidentally replying-all to a company-wide email thread that started in 2018, and at this point I'm too invested to stop.",
  "The neighbor's kid asked me what I do for a living, and after I explained, they said 'that can't possibly be a real job' — and honestly, fair.",
  "I found a receipt in my pocket from a store I've never visited, dated next Tuesday, for an item I've always secretly wanted.",
  "The HOA sent me a letter about my 'aggressively neutral' lawn decorations, which I interpret as both a complaint and a challenge.",
  "I accidentally set my out-of-office reply to 'I have left this dimension and will respond to your email upon my return,' and now I have to commit to the bit.",
  "My spam folder has been generating better story ideas than I have in the past six months.",
  "I attended a focus group that turned out to be a surprise intervention for someone named Gary — I am not Gary, but I stayed anyway.",
  "The 'I'm not a robot' CAPTCHA asked me to identify all squares containing regret, and I've never felt more seen.",
  "I found a Post-it note on my desk that said 'they know' in my own handwriting, and I have no memory of writing it.",
  "The elevator pitch competition at work was won by someone who pitched 'elevator pitches for elevator pitches,' and we all clapped in confused admiration.",
  "I've been using the same password for everything since 2009, and at this point it's less a security measure and more a time capsule.",
  "My calendar has been double-booked for the past three months, and I've just been attending whichever event has better snacks.",
  "I received a performance review that described me as 'a valuable member of the team whose contributions are difficult to articulate but impossible to replace,' which I'm still decoding.",

  // ============================================================
  // DIALOGUE OPENERS (100) — conversation starters
  // ============================================================

  // Confession/revelation (35)
  "'I didn't mean to adopt seven ferrets,' he said, 'but here we are.'",
  "'I know this looks bad,' she said, holding the smoking toaster, 'but I can explain — actually, no, I can't.'",
  "'You know that thing you've been searching for your whole life? I found it. And you're not going to like where.'",
  "'I haven't been entirely honest with you about my job,' he admitted, 'or my name, or where I'm actually from.'",
  "'The good news is I fixed the problem. The bad news is the problem was friends we made along the way.'",
  "'I've been leaving notes in your lunch for three years,' she confessed, 'and you've never once mentioned them.'",
  "'So I may have accidentally joined a witness protection program, and they're very insistent that I stay.'",
  "'The reason I'm always late isn't traffic — it's that I keep stopping to help lost tourists, and I've accidentally learned six languages.'",
  "'I didn't lose your grandmother's ring — I gave it to someone who needed it more, and I'd do it again.'",
  "'I've been pretending to understand cryptocurrency for eight years, and at this point I'm in too deep.'",
  "'The cat isn't really a cat,' she whispered, and I realized I'd never actually seen it blink.",
  "'For the past year, I've been secretly paying for the coffee of the person behind me in line, and today it was you.'",
  "'I've read your diary,' he said, 'not recently — years ago, when we were kids — and I've been trying to make things right ever since.'",
  "'You know how you've been getting mystery gifts on your birthday? That's been me, every year, since we stopped talking.'",
  "'I don't know how to tell you this, but your entire life is the result of a clerical error.'",
  "'I'm not actually your cousin — I've been filling in for your real cousin since the family reunion of 2019.'",
  "'Remember when you thought you lost your wallet in Paris? You didn't lose it. It was stolen. By me. And I'm ready to make amends.'",
  "'The reason I've been so cheerful lately is that I've been living a double life, and the other one is going great.'",
  "'I've been using your Netflix account for seven years, and I feel like we've grown close without you knowing.'",
  "'I know who's been leaving those origami animals on your desk every morning, and it's not who you think — it's me, and also it's a cry for help.'",
  "'The secret ingredient in my famous cookies is actually just following the recipe on the bag, and I've been living a lie.'",
  "'I speak fluent dolphin,' she said, 'and they have been trying to warn us about something for decades.'",
  "'I've been keeping a list of every time you made me laugh, and it's eleven thousand entries long.'",
  "'I didn't actually graduate from Harvard — I just really enjoy the architecture and started attending classes by accident.'",
  "'I've been pretending to like your cooking for three years, but honestly, your pasta is the best thing I've ever eaten — wait, why are you crying?'",
  "'I found your old letters in the attic and read them all, and I need you to know I would have written back.'",
  "'The fortune teller said I would meet someone who changed my life today, and then you walked in — but honestly, I was hoping for someone taller.'",
  "'I'm not a real doctor, but I played one in a community theater production, and I think that still counts in an emergency.'",
  "'I've been the one returning your lost items for the past five years, and I think the universe is trying to get us together.'",
  "'You know how your plants keep thriving despite your neglect? I've been sneaking in to water them. You're welcome.'",
  "'I quit my job to pursue my dream of doing absolutely nothing, and I've never been more successful.'",
  "'I think I accidentally raised myself while my parents were busy, and the results are mixed.'",
  "'I know what you did,' she said, 'and more importantly, I know why — and I probably would have done the same.'",
  "'I've been secretly feeding your sourdough starter for a year because I couldn't bear to watch another one die.'",
  "'The real reason I moved to this town is buried somewhere in the park, and I think it's time we dug it up together.'",

  // Warning/threat (30)
  "'Whatever you do,' she whispered, 'don't look at the security footage from last night.'",
  "'If you hear singing coming from the basement, no you didn't — just walk away and call me immediately.'",
  "'The last person who asked that question disappeared,' he said, 'but not in a mysterious way — they just moved to Florida.'",
  "'You can open any door in this house except the one at the end of the hall, and I need you to trust me on that.'",
  "'If the cat starts walking backward, leave the house. Don't pack, don't think — just go.'",
  "'I'm going to give you some advice that I wish someone had given me: never accept tea from someone who doesn't blink.'",
  "'There are three rules for surviving this job. I can only tell you the first two. You'll figure out the third when it's almost too late.'",
  "'If a stranger offers you a key, take it. You won't know what it opens until the moment you need it.'",
  "'Promise me you won't read the comments on your own obituary — I made that mistake once, and it's not worth it.'",
  "'The warning signs are always there,' he said, 'but they're written in a language you only learn after it's too late.'",
  "'Don't trust anyone who owns more than three identical outfits,' she said, 'and definitely don't trust anyone who owns exactly three.'",
  "'If you ever find yourself in a room with no windows and one door, check which side the hinges are on before you go through.'",
  "'The bridge is safe to cross exactly seventeen times, and I've already crossed it sixteen.'",
  "'Never make a deal with someone who smiles with their teeth but not their eyes,' he said, demonstrating exactly what he meant.",
  "'If the phone rings between 3:00 and 3:07 AM, let it ring. That's not for you, and answering it would be a commitment.'",
  "'Don't eat anything that glows. That sounds obvious, but you'd be surprised how many people need to hear it.'",
  "'The map is accurate except for the parts that aren't, and figuring out which parts those are is the whole trick.'",
  "'I'm legally required to tell you that continuing past this point will void the warranty on your existence.'",
  "'If you see a door that's slightly ajar in a place where doors shouldn't be, close it gently and pretend you didn't see anything.'",
  "'Don't apologize to the statues in the garden — they remember, and they will hold it against you.'",
  "'The golden rule of this town is simple: we don't talk about the annual pie contest, and we don't ask why the pies taste like memories.'",
  "'Whatever you hear in the attic at night, don't record it. The sound doesn't exist in digital form.'",
  "'If a librarian recommends a book that doesn't seem to exist in the catalog, read it anyway but don't try to check it out.'",
  "'The elevator goes to the thirteenth floor, but only if you're carrying something you're willing to lose.'",
  "'Never follow the same bird twice,' she advised, 'because the second time, it knows you're following.'",
  "'If your reflection starts moving independently, don't panic — just match its pace until it gets bored.'",
  "'The weather forecast for tomorrow is exactly whatever you're most afraid of,' he said, checking his phone.",
  "'Don't whistle in the woods after dark. It's not that something will answer — it's that you'll realize nothing does.'",
  "'Keep a light on in every room you're not using,' she advised, 'not to keep things out, but to keep things in.'",
  "'If you hear someone call your name in a place where no one knows you, no you didn't — turn around and walk the other way.'",

  // Humor/sarcasm (35)
  "'I'm not saying it's aliens,' she said, 'but I'm also not not saying it's aliens.'",
  "'Well, that went better than expected,' she said, standing in the smoldering ruins of what had been a very expensive laboratory.",
  "'I have a plan,' he announced, and everyone in the room who knew him immediately started updating their resumes.",
  "'Technically, it's not a lie if I believed it when I said it and only later realized I was wrong,' she explained.",
  "'I've made a terrible mistake,' he said, 'and I need your help — also your car, your savings, and your complete lack of judgment.'",
  "'On a scale of one to ten, how bad is it?' she asked, and he said 'pi,' which was somehow the most terrifying possible answer.",
  "'This is either going to work brilliantly or fail catastrophically,' she said, 'and either way, it's going to be hilarious.'",
  "'I respect your opinion,' he said, in a tone that made it absolutely clear that he did not respect my opinion.",
  "'Let me play devil's advocate,' she began, and I realized she'd been playing devil's advocate so long she'd forgotten whose side she was actually on.",
  "'I'm not procrastinating,' I explained, 'I'm allowing my ideas to marinate in the rich broth of my anxiety.'",
  "'We need to talk,' she said, and my soul briefly left my body to go live a simpler life as a houseplant.",
  "'I've been called worse,' he shrugged, 'probably in the last five minutes, if I'm being honest.'",
  "'The presentation is tomorrow? I thought it was next month,' I said, in a voice that was totally calm and not at all screaming internally.",
  "'Define 'disaster,'' she requested, and he pulled out a PowerPoint presentation with forty-seven slides.",
  "'I'm not lost — I'm on an unplanned adventure,' I explained to the park ranger who had found me three miles off the trail.",
  "'This meeting could have been an email,' he muttered, 'and that email could have been a thought, and that thought could have been nothing.'",
  "'I've done the math,' she said, 'and the math says we should have done this completely differently.'",
  "'My therapist will be hearing about this,' she announced, 'and frankly, so will my lawyer, my mother, and my very judgmental cat.'",
  "'For the record,' he said, 'I was against this plan from the start, and I have the receipts, the emails, and the slightly hysterical voice memos to prove it.'",
  "'I'm fine,' she said, in the universal tone that meant she was absolutely, categorically, the opposite of fine.",
  "'Let me be perfectly clear,' he began, before saying the most confusing thing I'd ever heard in my life.",
  "'How hard can it be?' she asked — four words that had launched a thousand disasters.",
  "'I've got a bad feeling about this,' he said, 'which I realize I say before literally everything, but this time I mean it.'",
  "'I'm listening,' she said, folding her arms in a way that communicated very clearly that she was not, in fact, listening.",
  "'There's been a slight change of plans,' he announced, 'by which I mean the original plan is on fire, both literally and metaphorically.'",
  "'I don't mean to be dramatic,' she began, before saying the most dramatic thing anyone had ever said.",
  "'I did not see that coming,' he admitted, 'which is embarrassing because that is literally my one job.'",
  "'The difference between genius and stupidity is results,' she explained, 'and unfortunately, we won't know which this is for another twenty minutes.'",
  "'Is this legal?' he asked. 'Probably not,' she replied, 'but I checked with a lawyer and they said it was interesting, which is almost as good.'",
  "'I'm going to do something incredibly stupid,' she announced, 'and I need you to be my witness — not to stop me, just to film it.'",
  "'You're taking this surprisingly well,' he observed. 'Oh, I'm not,' she replied, 'this is just the calm before the complete emotional collapse.'",
  "'I've got good news and bad news,' she said. 'The good news is I solved the problem. The bad news is I created seventeen new ones.'",
  "'To be fair,' he said, in a situation where fairness was the last thing anyone was thinking about.",
  "'I told you so,' she whispered, with the restraint of someone who had been waiting seven years to say those exact words.",
  "'That's a terrible idea,' he said, 'count me in.'",

  // ============================================================
  // MYSTERY HOOKS (75) — intriguing, strange, compelling
  // ============================================================

  // Discovery (25)
  "There was a door in the basement that hadn't been there the day before.",
  "She found a letter addressed to her in her grandmother's handwriting — dated three years after her grandmother had died.",
  "The suitcase in the attic contained nothing but photographs of people sleeping in what looked like her own bedroom.",
  "He discovered a room in his apartment that he'd never noticed before, and the calendar on the wall was set to next year.",
  "The book she found at the used bookstore had her name printed in the dedication — to someone who had died a century ago.",
  "They dug up the backyard to plant a garden and found a staircase that went down much farther than any basement should.",
  "The painting in the hotel room changed every time she looked at it, and it was getting closer.",
  "He found a USB drive taped under his desk labeled 'FOR YOU — WATCH ALONE.' The file was created the day he was born.",
  "The old typewriter in the antique shop had a piece of paper still in it, and the last sentence typed was unfinished.",
  "She found her own obituary in a newspaper from 1952, and the photo was unmistakably her.",
  "There was a key in the safe deposit box that her father had left her, and it didn't fit any lock in the known world.",
  "The mirror in the hotel bathroom showed a reflection that was just slightly delayed, as if reality was buffering.",
  "He found a map of his hometown in a library book, but it showed streets that didn't exist and buildings that had been demolished years ago.",
  "The recording on the old cassette tape started with her voice saying things she hadn't said yet, to a person she hadn't yet met.",
  "She discovered that every seventh photo on her phone contained the same face in the background — a face she'd never seen in person.",
  "The wall in the kitchen sounded hollow when she knocked, and behind it was a room that wasn't on any floor plan.",
  "He inherited a house from a relative he'd never heard of, and every room was perfectly preserved from a different decade.",
  "The old camera she bought at the estate sale still had film in it, and the developed photos showed places that don't exist.",
  "There was a locked drawer in the desk he'd used for twenty years, and he'd never noticed it until today.",
  "She found a notebook on the train filled with her own handwriting, describing events that hadn't happened yet.",
  "The safe behind the painting contained a single object: a Polaroid of her, taken from an angle that shouldn't have been possible.",
  "He discovered that the house he grew up in had an extra bedroom that everyone in his family remembered differently.",
  "The message in the bottle she found on the beach was dated tomorrow, and it was asking for help.",
  "There was a door in the airport that had no number and no sign, and the people who went through it didn't come back looking the same.",
  "She found her wedding ring inside a book she'd never read, three years before she met her husband.",

  // Pattern/conspiracy (25)
  "Every house on Maple Street received the same postcard on the same day, with the same three words: 'I'm coming home.'",
  "For the past month, the same person has appeared in the background of every live news broadcast, standing perfectly still.",
  "All the clocks in the building stopped at exactly the same moment, and no one can agree on what time it was.",
  "Every child born in this town in the past decade shares the same birthmark, and the pattern matches a constellation that wasn't discovered until last year.",
  "The man in the gray suit has been seen in seventeen different countries on the same day, and all the photographs are verified authentic.",
  "Someone has been replacing the books in the library with nearly identical copies that differ by exactly one word.",
  "The number patterns in her dreams were coordinates, and when she looked them up, every one pointed to the same empty field in Kansas.",
  "Every photograph taken in this town between 1973 and 1975 shows the same cloud formation in the background, regardless of the weather.",
  "The elevator in the office building has been stopping at the same floor every day at the same time, but no one gets on or off.",
  "Someone has been editing Wikipedia articles to insert a name that doesn't appear in any other record of human history.",
  "The songs on the radio have been playing in reverse order from the original broadcast schedule, and no one at the station will explain why.",
  "All the stray cats in the neighborhood have been gathering at the same intersection every night, waiting for someone who never arrives.",
  "The graffiti on the overpass changes every night, and it's been correctly predicting minor news events for three months.",
  "Every seventh caller to the radio station's request line has been requesting the same song since 1987.",
  "The pattern of lights in the office building across the street has been spelling out messages in Morse code that only she seems to notice.",
  "Census records show that exactly one person has lived in this apartment building in every decade since it was built — always the same name, always a different face.",
  "The tides have been arriving seventeen minutes early for the past six months, and the official explanation is 'under investigation.'",
  "Every mirror in the museum has been covered since 1964, and the docents have been trained to change the subject when asked why.",
  "The same bench in the park has been occupied by someone reading the same book for three years, but the reader is never the same person.",
  "The missing persons bulletin board at the post office has one photo that's been there since 1968, and the person in it hasn't aged.",
  "The local TV station still broadcasts a test pattern every night at 2 AM, and recently, something has started moving inside it.",
  "Every door in the hotel opens to the same hallway of a different hotel in a different city.",
  "The vending machines in the hospital sell items that don't exist in any catalog, and the prices are listed in a currency no one recognizes.",
  "The street performer has been playing the same song on the same corner for thirty years, and he hasn't aged a day.",
  "Every letter mailed from this town arrives at its destination exactly one day before it was sent.",

  // Unexplained phenomena (25)
  "The clock on the mantelpiece had been stopped at 3:47 for as long as anyone could remember — until today, when it started ticking backward.",
  "It rained every Tuesday at exactly 2 PM in this neighborhood, even when the sky was perfectly clear everywhere else.",
  "The shadow that followed him was slightly taller than he was, and sometimes it moved before he did.",
  "The echo in this canyon returns not your own voice, but the voice of the last person who stood where you're standing.",
  "Every night at 11:42, the power flickered in every house on the street for exactly one second, and no utility company could explain it.",
  "The old phone booth on the corner rang every Christmas Eve at midnight, and whoever answered heard the voice of someone they'd lost.",
  "The temperature in this room was always exactly seventy-two degrees, no matter the season, no matter the weather, no matter if the heating was on or off.",
  "The photographs she took all developed with the same faint figure in the distance — a person who appeared to be walking toward the camera.",
  "The scent of jasmine filled the subway station at random intervals, and every time it happened, someone fell in love.",
  "The wind in this valley carried whispers that could be understood in any language, but the messages were always different for everyone.",
  "A perfectly circular patch of grass in the park stayed green in winter and brown in summer, and scientists had stopped trying to explain it.",
  "The old elevator in the department store had buttons for floors that didn't exist, and the ones who'd pressed them had stories no one believed.",
  "Every baby born during a thunderstorm in this town has the same dream on their sixteenth birthday.",
  "The radio sometimes picked up stations that broadcast from decades in the past, and the news was always about events that still hadn't happened.",
  "A single tree in the forest produces fruit that tastes like your favorite childhood memory — different for everyone who tries it.",
  "The footsteps in the corridor stopped whenever she turned around, but the pattern in the dust suggested they'd been following her for hours.",
  "The streetlight at the corner flickers exactly three times whenever someone in the neighborhood is about to receive life-changing news.",
  "The fog that rolls in every October doesn't show up on radar, satellite, or any instrument — it's only visible to the human eye.",
  "The mural on the side of the library has been slowly changing over the years, and the artist who painted it died in 1967.",
  "Every mirror in the house shows a slightly different version of the room — a chair moved here, a book missing there — as if each one reflects a different timeline.",
  "The well in the old part of town shows stars in its water even at noon, and they don't match any known constellation.",
  "The new moon was supposed to be invisible tonight, but it was glowing faintly red, and every telescope in the world was pointed at it.",
  "The birds in this region sing in perfect four-part harmony, and ornithologists have given up trying to explain it.",
  "The water from the spring tastes different to everyone — some taste joy, some taste regret, and a few taste nothing at all.",
  "The dreams in this house are shared: whatever one person dreams, everyone else in the building dreams too — and last night, someone dreamed of fire.",
];
