/** 150 common English verbs (base/present tense form) for the Random Sentence Generator */
export const VERBS: string[] = [
  'accept', 'add', 'admire', 'admit', 'advise', 'agree', 'allow', 'answer',
  'appear', 'approach', 'arrive', 'ask', 'attack', 'bake', 'bathe', 'battle',
  'begin', 'behave', 'believe', 'belong', 'bend', 'bite', 'blow', 'boil',
  'borrow', 'break', 'bring', 'build', 'burn', 'buy', 'call', 'carry',
  'catch', 'change', 'chase', 'chew', 'choose', 'climb', 'close', 'collect',
  'come', 'command', 'compare', 'compete', 'cook', 'copy', 'count', 'cover',
  'create', 'cross', 'cry', 'cut', 'dance', 'decide', 'defend', 'deliver',
  'demand', 'describe', 'design', 'destroy', 'develop', 'dig', 'discover',
  'discuss', 'draw', 'dream', 'drink', 'drive', 'drop', 'eat', 'encourage',
  'enjoy', 'enter', 'escape', 'examine', 'exist', 'expect', 'explain',
  'explore', 'express', 'fail', 'fall', 'feed', 'feel', 'fight', 'fill',
  'find', 'finish', 'fix', 'fly', 'follow', 'force', 'forget', 'forgive',
  'form', 'freeze', 'gather', 'give', 'grab', 'greet', 'grow', 'guard',
  'guess', 'guide', 'handle', 'hang', 'hate', 'hear', 'help', 'hide', 'hit',
  'hold', 'hope', 'hunt', 'hurry', 'hurt', 'imagine', 'improve', 'include',
  'increase', 'influence', 'inform', 'invent', 'invite', 'join', 'jump',
  'keep', 'kick', 'kill', 'kiss', 'know', 'laugh', 'lay', 'lead', 'learn',
  'leave', 'lend', 'lift', 'like', 'listen', 'live', 'look', 'lose', 'love',
  'make', 'manage', 'mark', 'measure', 'meet', 'mention', 'miss', 'mix',
  'move', 'need', 'notice', 'obey', 'observe', 'offer', 'open', 'order',
  'own', 'pack', 'paint', 'park', 'pass', 'pay', 'perform', 'pick', 'place',
  'plan', 'play', 'point', 'polish', 'prepare', 'present', 'press', 'prevent',
  'print', 'produce', 'promise', 'protect', 'provide', 'pull', 'push', 'raise',
  'reach', 'read', 'receive', 'record', 'reduce', 'reflect', 'refuse',
  'remember', 'remove', 'repair', 'repeat', 'replace', 'report', 'represent',
  'request', 'require', 'rest', 'return', 'reveal', 'ride', 'ring', 'rise',
  'roll', 'run', 'save', 'search', 'see', 'sell', 'send', 'separate', 'serve',
  'settle', 'shake', 'share', 'shoot', 'shout', 'show', 'sing', 'sit',
  'sleep', 'smell', 'smile', 'speak', 'spend', 'stand', 'start', 'stay',
  'steal', 'stick', 'stop', 'store', 'stretch', 'strike', 'study', 'suffer',
  'suggest', 'supply', 'support', 'surround', 'survive', 'suspect', 'swim',
  'take', 'talk', 'taste', 'teach', 'test', 'thank', 'think', 'throw',
  'touch', 'trade', 'train', 'travel', 'treat', 'trust', 'try', 'turn',
  'understand', 'use', 'visit', 'wait', 'walk', 'want', 'warn', 'wash',
  'watch', 'wear', 'win', 'wish', 'wonder', 'work', 'worry', 'write',
];
